[build-system]
# setuptools 61.0.0 supports declaring package metadata in pyproject.toml.
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tox_egg_info_demo"
version = "0.0.1"

[tool.setuptools.package-data]
tox_egg_info_demo = ["hello.txt"]
